USE Projekt;

IF OBJECT_ID('FACT_RIDE', 'U') IS NOT NULL 
DROP TABLE FACT_RIDE;

IF OBJECT_ID('BulkCSVTaxiImported', 'U') IS NOT NULL 
  DROP TABLE BulkCSVTaxiImported; 

IF OBJECT_ID('BulkCSVBikeImported', 'U') IS NOT NULL 
  DROP TABLE BulkCSVBikeImported; 

IF OBJECT_ID('BulkCSVImported', 'U') IS NOT NULL 
  DROP TABLE BulkCSVImported; 

IF OBJECT_ID('Months', 'U') IS NOT NULL 
  DROP TABLE Months; 

IF OBJECT_ID('DaysOfWeek', 'U') IS NOT NULL 
  DROP TABLE DaysOfWeek; 

IF OBJECT_ID('DIM_DATE', 'U') IS NOT NULL 
DROP TABLE DIM_DATE; 

IF OBJECT_ID('DIM_TIME', 'U') IS NOT NULL 
DROP TABLE DIM_TIME; 

IF OBJECT_ID('DIM_LOCATION', 'U') IS NOT NULL 
DROP TABLE DIM_LOCATION; 

IF OBJECT_ID('DIM_WEATHER', 'U') IS NOT NULL 
DROP TABLE DIM_WEATHER; 

IF OBJECT_ID('DIM_CAB', 'U') IS NOT NULL 
DROP TABLE DIM_CAB; 